FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./package.json
RUN npm install
RUN mkdir -p /app/node_modules/.cache && chown node:node /app/node_modules/.cache
# RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
# RUN chown -R node:node /app/node_modules
COPY . .
CMD ["npm", "run", "start"]